### ISSUE TITLE
[redocly/openapi-cli] 'test' does not fail when type:array and no items

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-api-spec#111]
The following example is validated as successful:
```yaml
     stdout_command:
       type: array
       description: list of commands executed in the stage
```

when `items` property is missing. This is wrong as can be tested in https://editor.swagger.io/

Seen with `redocly/openapi-cli` version: **^1.0.0-beta.5**
